### PR TITLE
Added compression support for Memcache driver

### PR DESCRIPTION
**Pull request by misternerd**
- Added config field: compress_data
- If compress_data is set, enabled compression in Memcache driver

### CODE REVIEW

**Comment by Geolim4** [comment]
Can you pr to the v5 too please ?
Thanks you :)

**Comment by misternerd** [comment]
I just pushed another PR to the V5 branch, should I close this one?

**Comment by khoaofgod** [comment]
@misternerd our plan are keep v4 for 2 more years, they need both update. @thanks for your help on this bro

**Comment by Geolim4** [comment]
@misternerd  It's almost perfect, can you replaced private by protected please ? Else it wont allow class extends :)

**Comment by Geolim4** [comment]
Nevermind, my IDE is open, i will do it finally :)

**Comment by Geolim4** [comment]
Done.

**Pull request merged**
