### PR TITLE
Fix the Sqlite driver is unable to fetch expired items

### PR DESCRIPTION
**Pull request by jfcherng**
Due to this issue, an expired item is impossible to be deleted.

### CODE REVIEW

**Comment by khoaofgod** [comment]
@jfcherng 
The select should not return these expired items. So, I don't think is a change need.
Because on deleting, it will remove expired already.

https://github.com/jfcherng/phpfastcache/blob/b79746493099632440110b568022e638433d6228/src/phpFastCache/Drivers/Sqlite/Driver.php#L350

**Comment by jfcherng** [comment]
That line won't be executed.

> For an expired item, $driver->deleteItem($key) is
not working because $driver->driverRead($item) always
returns null in $driver->getItem($key).

Or, there is another flow/mechanism to reach `$driver->driverDelete($item)` except `$driver->deleteItem($key)`?

**Comment by khoaofgod** [comment]
I see, @jfcherng 
On v4, after/before I do select, I also delete old exp items first.

@Geolim4 : Can you take a look at this PR.

**Comment by khoaofgod** [comment]
@Geolim4 
This file:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L66

Line 66,
as @jfcherng said, $item->isExpired() is always FALSE, since it won't return expired items from driverRead();
However, after @jfcherng  changed, it will return TRUE there.
Lead to line 74:  $this->driverDelete($item);

My question is:
** After we do driverDelete($item) there, what should we return? 
** Or we just leave it like that, and it still does well?

**Comment by jfcherng** [comment]
> My question is:
** Or we just leave it like that, and it still does well?

Do we need to add `$this->itemInstances[ $key ]->setHit(false);` right after `driverDelete($item)` [here](https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L75)?

**Comment by khoaofgod** [comment]
Oh yeah, we have to wait for @Geolim4 test this code and merge, because he's the lead developer on v5. He wrote the whole thing of v5. Hahaha.

**Comment by Geolim4** [comment]
@jfcherng Thanks you for the fix, you totally right, the code will never being executed due to this specific statement. Can you PR' on the V 5.1 too please ?

Thanks you,
Georges

**Comment by Geolim4** [comment]
> Do we need to add $this->itemInstances[$key]->setHit(false); right after driverDelete($item) here?
Not needed, it's already done here :)

https://github.com/PHPSocialNetwork/phpfastcache/blob/c414beb1282e3c2bca930088a9f82e6c975f48c0/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L152

**Comment by jfcherng** [comment]
> Thanks you for the fix, you totally right, the code will never being executed due to this specific statement. Can you PR' on the V 5.1 too please ?

@Geolim4 Sure :+1:

**Comment by Geolim4** [comment]
Perfect thanks you

**Pull request merged**
