### PR TITLE
optimized code

### PR DESCRIPTION
**Pull request by Golodnyi**

### CODE REVIEW

**Comment by Geolim4** [comment]
Thanks, I will have a look tonigh, in the meantime can you PR on V6 too please ?

Thanks you !

**Comment by Geolim4** [comment]
@Golodnyi Looks fine, I'm gonna merge it, can you Pr on the V6 please ? :)

**Comment by Golodnyi** [comment]
i send PR on V6

**Comment by Geolim4** [comment]
Why did you closed the Pr, I did not merged yet :)
Can i reopen it ?

**Comment by Golodnyi** [comment]
Reopen)

**Comment by Geolim4** [comment]
Thanks, I also made a Pr on my side to prevent any regression on disk-based drivers.

**Pull request merged**
