### PR TITLE
PHP 7.4 support

### PR DESCRIPTION
**Pull request by AntiEngineer**
## Proposed changes

Removes deprecation notice.

## Types of changes

What types of changes does your code introduce to Phpfastcache?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing code/behavior)
- [ ] Deprecated third party dependency update
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation/Typo/Resource update that does not involve any code modification

## Agreement

I have read the [CONTRIBUTING](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md) and [CODING GUIDELINE](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODING_GUIDELINE.md) docs

### CODE REVIEW

**Comment by AntiEngineer** [comment]
There you go @Geolim4.

**Comment by AntiEngineer** [comment]
Side note: breaks PHP 7.0 since looks like the method isn't there.

**Comment by AntiEngineer** [comment]
There it is. 

In versions where getName isn't present, it'll fall back to __toString.

Cheers.

**Comment by Geolim4** [comment]
> 
> 
> Side note: breaks PHP 7.0 since looks like the method isn't there.

Hehe that's why the Travis CI is here ;)

Thanks, I'm reviewing this PR !

**Pull request merged**
